name: My Notes
url: http://ogaclejapan.com
baseurl: 
timezone: Asia/Tokyo
encoding: utf-8

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "tables", "fenced_code_blocks"]

pygments: true
permalink: pretty
paginate: 5

owner : 
  name : ogaclejapan
  github : ogaclejapan
  twitter : ogaclejapan
#  googleplus : 
#  facebook : 

# See http://schema.org/Article
schema_article_type : Article

google_analytics :
  tracking_id : 'UA-37241684-1'

addthis:
  pub_id: 'ra-52b998c30d780542'

exclude: ["README.md", "LICENSE", ".gitignore", "s3_website.yml", "images"]
